#!/bin/bash
set -e

echo "This project uses ko for container builds. No Dockerfile needed!"
echo ""
echo "To build with ko:"
echo "  ko build --local --bare ."
echo ""
echo "To build and run with ko:"
echo "  KO_DOCKER_REPO=ko.local ko run --local --bare ."
echo ""
echo "To build and push to a registry:"
echo "  export KO_DOCKER_REPO=ghcr.io/your-github-username/cloud-run-service-go"
echo "  ko build --bare ."
echo ""
echo "Or use the Makefile:"
echo "  make ko-build      # Build locally"
echo "  make ko-run        # Build and run locally"
echo "  make ko-publish    # Build and push to registry"
echo ""
echo "For legacy Docker builds (not recommended):"
echo "  docker build -t cloud-run-service-go:latest ."
echo ""
echo "To deploy to Google Cloud Run:"
echo "  Push to main branch to trigger automatic deployment via GitHub Actions"
echo "  OR manually: gcloud run deploy cloud-run-service-go --image=\$(ko build --bare .)"
